In [3]:
import numpy as np
from scipy import stats
rng = np.random.default_rng()
sample1 = stats.uniform.rvs(size=100, random_state=rng)
sample2 = stats.norm.rvs(size=110, random_state=rng)
response = stats.ks_2samp(sample1, sample2)

In [4]:
response

KstestResult(statistic=0.4909090909090909, pvalue=5.299121458261447e-12)

In [5]:
sample1

array([0.93908645, 0.67597184, 0.04976122, 0.22161016, 0.6861759 ,
       0.5062167 , 0.58046342, 0.37012559, 0.3405442 , 0.77249022,
       0.47983807, 0.79649431, 0.23774102, 0.50539298, 0.51788274,
       0.25473665, 0.46258803, 0.96417014, 0.85327966, 0.66858913,
       0.05830672, 0.2114372 , 0.31918837, 0.26587207, 0.8643604 ,
       0.64184838, 0.70913156, 0.21148133, 0.45429717, 0.34327341,
       0.0960792 , 0.19991373, 0.72559864, 0.82809133, 0.12044231,
       0.68662885, 0.43096303, 0.55035119, 0.85680265, 0.67632867,
       0.92246039, 0.32541575, 0.44297447, 0.82275982, 0.13603194,
       0.86723876, 0.91243949, 0.64241765, 0.98565793, 0.99539404,
       0.87649275, 0.6740925 , 0.95606519, 0.3489683 , 0.76582766,
       0.99000382, 0.16716943, 0.16980997, 0.6955171 , 0.58611731,
       0.52136237, 0.47217118, 0.0406459 , 0.13639652, 0.46398797,
       0.20884505, 0.01888283, 0.3280623 , 0.20475286, 0.67062328,
       0.23175234, 0.37830324, 0.15492078, 0.90729441, 0.23739

In [6]:
sample2

array([-0.36335508, -0.78674063, -0.16248359,  0.11370672,  0.31426149,
       -0.21118746,  0.28768432,  0.77338967,  1.25824883,  0.08827049,
        0.20338167, -0.42184864,  1.00556487,  0.70730016,  0.53547594,
       -0.0744456 , -0.09257956, -0.77275805,  0.47726927, -0.86172101,
       -1.7602833 ,  0.23914853,  0.24379859,  0.41525025,  0.07946342,
        0.47998394,  1.64023492, -0.56668279,  1.11298892, -0.71879473,
       -1.59097762, -2.02956131,  0.11520858, -0.0839724 ,  2.27867184,
       -1.21522179,  0.81673593,  1.1961199 ,  1.20816157, -0.69672713,
        0.56809004,  1.17257725,  0.85988035, -1.35183027, -0.7099593 ,
        0.05178819,  0.48696382, -0.83829244,  2.05032799,  1.56187494,
       -1.9274303 , -1.03254461, -0.13875103, -0.59696802, -0.44768712,
        0.10434669,  1.8564738 , -0.34157781,  0.48234918, -1.47344986,
       -0.80868736, -0.73642756,  0.42558286,  0.93315523,  1.26917217,
        1.12002853, -2.76081147, -0.59560037, -0.18410027, -0.19

In [7]:
response.pvalue

5.299121458261447e-12

In [13]:
round(response.pvalue,4)

0.0

In [14]:
# if pvalue will be more then the o.05 then we can say that the distribution of both the data is same-->no need to retrain the data 
# if pvalue will be less then the o.05 then we can say that the distribution of the data has changed-->need to retrain the data 

In [15]:
# Anomly in my data set 
'''
1. High nall value 
2. missing columns
3. outlier
4. categorical:
gender--> male, female, other

'''

'\n1. High nall value \n2. missing columns\n3. outlier\n4. categorical:\ngender--> male, female, other\n\n'

In [16]:
# Drift:- decay of Model's prediction power due to change in the real world dataset(enveronmnt).
# target Drift:- change in the target variable.
# concept drift- decay of Model's prediction power due to changes in the relationship between the target variable and input features.

In [2]:
import pandas as pd

In [3]:
df= pd.read_csv("/config/workspace/artifact/12092022__235150/data_ingestion/dataset/train.csv")

In [5]:
df.isnull().sum()

class         0
aa_000        0
ab_000    22365
ac_000     1702
ad_000     7314
          ...  
ee_007      308
ee_008      308
ee_009      308
ef_000     1382
eg_000     1381
Length: 171, dtype: int64

In [6]:
#percentage of null values
df.isnull().sum()/df.shape[0]

class     0.000000
aa_000    0.000000
ab_000    0.772539
ac_000    0.058791
ad_000    0.252642
            ...   
ee_007    0.010639
ee_008    0.010639
ee_009    0.010639
ef_000    0.047737
eg_000    0.047703
Length: 171, dtype: float64

In [8]:
(df.isnull().sum()/df.shape[0]).values

array([0.        , 0.        , 0.77253886, 0.05879102, 0.25264249,
       0.0435924 , 0.0435924 , 0.01063903, 0.01063903, 0.01063903,
       0.01063903, 0.01063903, 0.01063903, 0.01063903, 0.01063903,
       0.01063903, 0.01063903, 0.01056995, 0.01046632, 0.01046632,
       0.07644214, 0.01053541, 0.01046632, 0.01053541, 0.00963731,
       0.01053541, 0.00963731, 0.04770294, 0.01046632, 0.01046632,
       0.01046632, 0.0435924 , 0.0435924 , 0.01063903, 0.01063903,
       0.01063903, 0.01063903, 0.01063903, 0.01063903, 0.01063903,
       0.01063903, 0.01063903, 0.01063903, 0.01063903, 0.01063903,
       0.01063903, 0.01063903, 0.01063903, 0.01063903, 0.01063903,
       0.01063903, 0.01063903, 0.01063903, 0.01084629, 0.01084629,
       0.01084629, 0.01084629, 0.01084629, 0.01084629, 0.01084629,
       0.01084629, 0.01084629, 0.01084629, 0.01056995, 0.04777202,
       0.04777202, 0.04369603, 0.0435924 , 0.01053541, 0.01053541,
       0.00963731, 0.00963731, 0.38165803, 0.45008636, 0.65488

In [9]:
(df.isnull().sum()/df.shape[0]).values.__len__()

171

In [11]:
(df.isnull().sum()/df.shape[0]).index

Index(['class', 'aa_000', 'ab_000', 'ac_000', 'ad_000', 'ae_000', 'af_000',
       'ag_000', 'ag_001', 'ag_002',
       ...
       'ee_002', 'ee_003', 'ee_004', 'ee_005', 'ee_006', 'ee_007', 'ee_008',
       'ee_009', 'ef_000', 'eg_000'],
      dtype='object', length=171)

In [15]:
l1=[1,2,3]
l2=[3,4,5]
for l1_val, l2_val in zip(l1,l2):
    print(l1_val, l2_val)

1 3
2 4
3 5


In [17]:
drop_column_names= []
for column_name, missing_percentage in zip((df.isnull().sum()/df.shape[0]).index,(df.isnull().sum()/df.shape[0]).values):
    print(column_name, missing_percentage)
    
    if missing_percentage > 0.3:
        drop_column_names.append(column_name)

class 0.0
aa_000 0.0
ab_000 0.7725388601036269
ac_000 0.05879101899827288
ad_000 0.2526424870466321
ae_000 0.043592400690846286
af_000 0.043592400690846286
ag_000 0.010639032815198618
ag_001 0.010639032815198618
ag_002 0.010639032815198618
ag_003 0.010639032815198618
ag_004 0.010639032815198618
ag_005 0.010639032815198618
ag_006 0.010639032815198618
ag_007 0.010639032815198618
ag_008 0.010639032815198618
ag_009 0.010639032815198618
ah_000 0.010569948186528497
ai_000 0.010466321243523317
aj_000 0.010466321243523317
ak_000 0.07644214162348878
al_000 0.010535405872193437
am_0 0.010466321243523317
an_000 0.010535405872193437
ao_000 0.009637305699481865
ap_000 0.010535405872193437
aq_000 0.009637305699481865
ar_000 0.04770293609671848
as_000 0.010466321243523317
at_000 0.010466321243523317
au_000 0.010466321243523317
av_000 0.043592400690846286
ax_000 0.043592400690846286
ay_000 0.010639032815198618
ay_001 0.010639032815198618
ay_002 0.010639032815198618
ay_003 0.010639032815198618
ay_004 0

In [18]:
drop_column_names

['ab_000',
 'bk_000',
 'bl_000',
 'bm_000',
 'bn_000',
 'bo_000',
 'bp_000',
 'bq_000',
 'br_000',
 'cr_000']

In [4]:
null_report = df.isna().sum()/df.shape[0]


In [5]:
drop_column_names = null_report[null_report>0.3].index

In [30]:
drop_column_names

Index(['ab_000', 'bk_000', 'bl_000', 'bm_000', 'bn_000', 'bo_000', 'bp_000',
       'bq_000', 'br_000', 'cr_000'],
      dtype='object')

In [9]:
df.iloc[:,[0]].drop("class",axis=1).columns

Index([], dtype='object')

In [11]:
if len(df.columns)==0:
    return None

SyntaxError: 'return' outside function (1549379931.py, line 2)

In [2]:
from glob import glob

In [5]:
glob("/config/workspace/saved_models/1/**/*.pkl")

['/config/workspace/saved_models/1/model/model.pkl']

In [6]:
import os

In [7]:
os.path.basename("saved_model/1")

'1'